server:
  port: 8080  # Gateway will run here

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    name: api-gateway  # Service name in Eureka
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service  # "lb" = load balancing via Eureka
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1  # Removes "/api/users" before forwarding

        - id: car-service
          uri: lb://CAR-SERVICE
          predicates:
            - Path=/api/cars/**
          filters:
            - StripPrefix=1

# Connect to Eureka Server
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/